### ISSUE TITLE
Error when adding spike template with sprout

### ISSUE THREAD

**Issue by benod3107** [static-dev/spike-tpl-base#37]
When adding the spike-tpl-base via sprout it throws an error:
$ sprout add spike-tpl-base git@github.com:static-dev/spike-tpl-base.git

✘ Error: Command failed: git clone --recursive git@github.com:static-dev/spike-tpl-base.git /Users/benodonohue/.config/sprout/spike-tpl-base
Cloning into '/Users/benodonohue/.config/sprout/spike-tpl-base'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Any suggestions? 

<img width="894" alt="screen shot 2016-06-23 at 11 13 56 am" src="https://cloud.githubusercontent.com/assets/16271128/16288902/c888cd64-3933-11e6-8ee3-3185c66b9516.png">

**Comment by jescalan** [comment]
So the error is telling you exactly what's wrong, you are trying to use a SSH url without having added your SSH keys, so you are getting permission denied. I'd try using the https url instead, or adding your SSH keys 😁

**Comment by jescalan** [comment]
Oh also if you're trying to use spike, you can just run `spike new` and it will generate a project with this template!

**Comment by benod3107** [comment]
Thanks Jeff, I just decided to continue with $ spike new 👍
