### ISSUE TITLE
spike in package json by default?

### ISSUE THREAD

**Issue by dbox** [static-dev/spike-tpl-base#55]
Should Spike be in package.json by default since Netlify requires it? Let me know and I can PR.

**Comment by jescalan** [comment]
I don't think so, it's a big extra dependency and not everyone is using netlify. I'd say just add it if you are going to netlify later 😁

**Comment by dbox** [comment]
Gotcha. Took me forever to realize why my build was failing.

**Comment by jescalan** [comment]
Maybe we can add a note to the readme about this somewhere? I feel like you aren't the only one who will run into this...

**Comment by dbox** [comment]
Yeah just somwehere obvious.. But i'm not sure even having it in readme for this repo is right place... I'll think on it.

**Comment by jescalan** [comment]
👍
