### ISSUE TITLE
Template refers to scopeHosting

### ISSUE THREAD

**Issue by anthonyjclark** [static-dev/spike-tpl-base#76]
https://github.com/static-dev/spike-tpl-base/blob/f5328f80f907f661a019c1a22081cb242eb56cc6/root/app.production.js#L6

The line referenced above should be:

```js
      scopeHoisting: true,
```

This will make it (**correctly**) match the documentation for `spike-optimize`.

**Comment by jescalan** [comment]
Ah thanks for catching this! Want to PR the fix and claim the credit? 😁

**Comment by anthonyjclark** [comment]
Sure. I'll do so sometime in the next few days.
